name: E2E Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Run Playwright tests
    container:
      image: mcr.microsoft.com/playwright:v1.41.2-jammy
    services:
      database: 
        image: mysql:5.7
        env:
          MYSQL_DATABASE: menugenius
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: menugenius
      DB_USERNAME: root
      DB_PASSWORD: password

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4

    - uses: shivammathur/setup-php@v2

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./Frontend
    
    - name: Build project
      run: npm run build
      working-directory: ./Frontend
    
    - name: Install backend dependencies
      run: composer install
      working-directory: ./Backend
    
    - name: Initialize database
      run: php artisan migrate:fresh
      working-directory: ./Backend

    - name: Start backend
      run: php artisan serve &
      working-directory: ./Backend
    
    - name: Run Playwright tests
      run: npm run test
      working-directory: ./Frontend
